{{cookiecutter.app_name}}:
  enabled: true
  nameOverride: {{cookiecutter.app_name}}
  replicaCount: 1
  resources:
    limits:
      cpu: 1
      memory: 750Mi
    requests:
      cpu: 20m
      memory: 500Mi
  image:
    repository: gcr.io/pledge-dev-267910/{{cookiecutter.app_name}}
    tag: latest